apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: same-indent-template
spec:
  entrypoint: same-indent-main
  templates:
  - name: same-indent-main
    dag:
      tasks:
      - name: first-task
        templateRef:
          name: same-indent-helper
          template: helper-step
      - name: second-task
        dependencies: [first-task]
        template: local-step
  - name: local-step
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        print("hello")
